export const NIGERIAN_STATES = [
  {
    state: 'Abia',
    capital: 'Umuahia',
    lgas: [
      { name: 'Aba North', postal_code: '440001' },
      { name: 'Aba South', postal_code: '440001' },
      { name: 'Arochukwu', postal_code: '440001' },
      { name: 'Bende', postal_code: '440001' },
      { name: 'Ikwuano', postal_code: '440001' },
      { name: 'Isiala Ngwa North', postal_code: '440001' },
      { name: 'Isiala Ngwa South', postal_code: '440001' },
      { name: 'Isuikwuato', postal_code: '440001' },
      { name: 'Obi Ngwa', postal_code: '440001' },
      { name: 'Ohafia', postal_code: '440001' },
      { name: 'Osisioma', postal_code: '440001' },
      { name: 'Ugwunagbo', postal_code: '440001' },
      { name: 'Ukwa East', postal_code: '440001' },
      { name: 'Ukwa West', postal_code: '440001' },
      { name: 'Umuahia North', postal_code: '440001' },
      { name: 'Umuahia South', postal_code: '440001' },
      { name: 'Umu Nneochi', postal_code: '440001' },
    ],
  },
  {
    state: 'Adamawa',
    capital: 'Yola',
    lgas: [
      { name: 'Demsa', postal_code: '640001' },
      { name: 'Fufure', postal_code: '640001' },
      { name: 'Ganye', postal_code: '640001' },
      { name: 'Gayuk', postal_code: '640001' },
      { name: 'Gombi', postal_code: '640001' },
      { name: 'Grie', postal_code: '640001' },
      { name: 'Hong', postal_code: '640001' },
      { name: 'Jada', postal_code: '640001' },
      { name: 'Lamurde', postal_code: '640001' },
      { name: 'Madagali', postal_code: '640001' },
      { name: 'Maiha', postal_code: '640001' },
      { name: 'Mayo Belwa', postal_code: '640001' },
      { name: 'Michika', postal_code: '640001' },
      { name: 'Mubi North', postal_code: '640001' },
      { name: 'Mubi South', postal_code: '640001' },
      { name: 'Numan', postal_code: '640001' },
      { name: 'Shelleng', postal_code: '640001' },
      { name: 'Song', postal_code: '640001' },
      { name: 'Toungo', postal_code: '640001' },
      { name: 'Yola North', postal_code: '640001' },
      { name: 'Yola South', postal_code: '640001' },
    ],
  },
  {
    state: 'Akwa Ibom',
    capital: 'Uyo',
    lgas: [
      { name: 'Abak', postal_code: '520001' },
      { name: 'Eastern Obolo', postal_code: '520001' },
      { name: 'Eket', postal_code: '520001' },
      { name: 'Esit Eket', postal_code: '520001' },
      { name: 'Essien Udim', postal_code: '520001' },
      { name: 'Etim Ekpo', postal_code: '520001' },
      { name: 'Etinan', postal_code: '520001' },
      { name: 'Ibeno', postal_code: '520001' },
      { name: 'Ibesikpo Asutan', postal_code: '520001' },
      { name: 'Ibiono-Ibom', postal_code: '520001' },
      { name: 'Ika', postal_code: '520001' },
      { name: 'Ikono', postal_code: '520001' },
      { name: 'Ikot Abasi', postal_code: '520001' },
      { name: 'Ikot Ekpene', postal_code: '520001' },
      { name: 'Ini', postal_code: '520001' },
      { name: 'Itu', postal_code: '520001' },
      { name: 'Mbo', postal_code: '520001' },
      { name: 'Mkpat-Enin', postal_code: '520001' },
      { name: 'Nsit-Atai', postal_code: '520001' },
      { name: 'Nsit-Ibom', postal_code: '520001' },
      { name: 'Nsit-Ubium', postal_code: '520001' },
      { name: 'Obot Akara', postal_code: '520001' },
      { name: 'Okobo', postal_code: '520001' },
      { name: 'Onna', postal_code: '520001' },
      { name: 'Oron', postal_code: '520001' },
      { name: 'Oruk Anam', postal_code: '520001' },
      { name: 'Udung-Uko', postal_code: '520001' },
      { name: 'Ukanafun', postal_code: '520001' },
      { name: 'Uruan', postal_code: '520001' },
      { name: 'Urue-Offong/Oruko', postal_code: '520001' },
      { name: 'Uyo', postal_code: '520001' },
    ],
  },
  {
    state: 'Anambra',
    capital: 'Awka',
    lgas: [
      { name: 'Aguata', postal_code: '420001' },
      { name: 'Anambra East', postal_code: '420001' },
      { name: 'Anambra West', postal_code: '420001' },
      { name: 'Anaocha', postal_code: '420001' },
      { name: 'Awka North', postal_code: '420001' },
      { name: 'Awka South', postal_code: '420001' },
      { name: 'Ayamelum', postal_code: '420001' },
      { name: 'Dunukofia', postal_code: '420001' },
      { name: 'Ekwusigo', postal_code: '420001' },
      { name: 'Idemili North', postal_code: '420001' },
      { name: 'Idemili South', postal_code: '420001' },
      { name: 'Ihiala', postal_code: '420001' },
      { name: 'Njikoka', postal_code: '420001' },
      { name: 'Nnewi North', postal_code: '420001' },
      { name: 'Nnewi South', postal_code: '420001' },
      { name: 'Ogbaru', postal_code: '420001' },
      { name: 'Onitsha North', postal_code: '420001' },
      { name: 'Onitsha South', postal_code: '420001' },
      { name: 'Orumba North', postal_code: '420001' },
      { name: 'Orumba South', postal_code: '420001' },
      { name: 'Oyi', postal_code: '420001' },
    ],
  },
  {
    state: 'Bauchi',
    capital: 'Bauchi',
    lgas: [
      { name: 'Alkaleri', postal_code: '740001' },
      { name: 'Bauchi', postal_code: '740001' },
      { name: 'Bogoro', postal_code: '740001' },
      { name: 'Damban', postal_code: '740001' },
      { name: 'Darazo', postal_code: '740001' },
      { name: 'Dass', postal_code: '740001' },
      { name: 'Gamawa', postal_code: '740001' },
      { name: 'Ganjuwa', postal_code: '740001' },
      { name: 'Giade', postal_code: '740001' },
      { name: 'Itas/Gadau', postal_code: '740001' },
      { name: "Jama'are", postal_code: '740001' },
      { name: 'Katagum', postal_code: '740001' },
      { name: 'Kirfi', postal_code: '740001' },
      { name: 'Misau', postal_code: '740001' },
      { name: 'Ningi', postal_code: '740001' },
      { name: 'Shira', postal_code: '740001' },
      { name: 'Tafawa Balewa', postal_code: '740001' },
      { name: 'Toro', postal_code: '740001' },
      { name: 'Warji', postal_code: '740001' },
      { name: 'Zaki', postal_code: '740001' },
    ],
  },
  {
    state: 'Bayelsa',
    capital: 'Yenagoa',
    lgas: [
      { name: 'Brass', postal_code: '561001' },
      { name: 'Ekeremor', postal_code: '561001' },
      { name: 'Kolokuma/Opokuma', postal_code: '561001' },
      { name: 'Nembe', postal_code: '561001' },
      { name: 'Ogbia', postal_code: '561001' },
      { name: 'Sagbama', postal_code: '561001' },
      { name: 'Southern Ijaw', postal_code: '561001' },
      { name: 'Yenagoa', postal_code: '561001' },
    ],
  },
  {
    state: 'Benue',
    capital: 'Makurdi',
    lgas: [
      { name: 'Ado', postal_code: '970001' },
      { name: 'Agatu', postal_code: '970001' },
      { name: 'Apa', postal_code: '970001' },
      { name: 'Buruku', postal_code: '970001' },
      { name: 'Gboko', postal_code: '970001' },
      { name: 'Guma', postal_code: '970001' },
      { name: 'Gwer East', postal_code: '970001' },
      { name: 'Gwer West', postal_code: '970001' },
      { name: 'Katsina-Ala', postal_code: '970001' },
      { name: 'Konshisha', postal_code: '970001' },
      { name: 'Kwande', postal_code: '970001' },
      { name: 'Logo', postal_code: '970001' },
      { name: 'Makurdi', postal_code: '970001' },
      { name: 'Obi', postal_code: '970001' },
      { name: 'Ogbadibo', postal_code: '970001' },
      { name: 'Ohimini', postal_code: '970001' },
      { name: 'Oju', postal_code: '970001' },
      { name: 'Okpokwu', postal_code: '970001' },
      { name: 'Otukpo', postal_code: '970001' },
      { name: 'Tarka', postal_code: '970001' },
      { name: 'Ukum', postal_code: '970001' },
      { name: 'Ushongo', postal_code: '970001' },
      { name: 'Vandeikya', postal_code: '970001' },
    ],
  },
  {
    state: 'Borno',
    capital: 'Maiduguri',
    lgas: [
      { name: 'Abadam', postal_code: '600001' },
      { name: 'Askira/Uba', postal_code: '600001' },
      { name: 'Bama', postal_code: '600001' },
      { name: 'Bayo', postal_code: '600001' },
      { name: 'Biu', postal_code: '600001' },
      { name: 'Chibok', postal_code: '600001' },
      { name: 'Damboa', postal_code: '600001' },
      { name: 'Dikwa', postal_code: '600001' },
      { name: 'Gubio', postal_code: '600001' },
      { name: 'Guzamala', postal_code: '600001' },
      { name: 'Gwoza', postal_code: '600001' },
      { name: 'Hawul', postal_code: '600001' },
      { name: 'Jere', postal_code: '600001' },
      { name: 'Kaga', postal_code: '600001' },
      { name: 'Kala/Balge', postal_code: '600001' },
      { name: 'Konduga', postal_code: '600001' },
      { name: 'Kukawa', postal_code: '600001' },
      { name: 'Kwaya Kusar', postal_code: '600001' },
      { name: 'Mafa', postal_code: '600001' },
      { name: 'Magumeri', postal_code: '600001' },
      { name: 'Maiduguri', postal_code: '600001' },
      { name: 'Marte', postal_code: '600001' },
      { name: 'Mobbar', postal_code: '600001' },
      { name: 'Monguno', postal_code: '600001' },
      { name: 'Ngala', postal_code: '600001' },
      { name: 'Nganzai', postal_code: '600001' },
      { name: 'Shani', postal_code: '600001' },
    ],
  },
  {
    state: 'Cross River',
    capital: 'Calabar',
    lgas: [
      { name: 'Abi', postal_code: '540001' },
      { name: 'Akamkpa', postal_code: '540001' },
      { name: 'Akpabuyo', postal_code: '540001' },
      { name: 'Bakassi', postal_code: '540001' },
      { name: 'Bekwarra', postal_code: '540001' },
      { name: 'Biase', postal_code: '540001' },
      { name: 'Boki', postal_code: '540001' },
      { name: 'Calabar Municipal', postal_code: '540001' },
      { name: 'Calabar South', postal_code: '540001' },
      { name: 'Etung', postal_code: '540001' },
      { name: 'Ikom', postal_code: '540001' },
      { name: 'Obanliku', postal_code: '540001' },
      { name: 'Obubra', postal_code: '540001' },
      { name: 'Obudu', postal_code: '540001' },
      { name: 'Odukpani', postal_code: '540001' },
      { name: 'Ogoja', postal_code: '540001' },
      { name: 'Yakuur', postal_code: '540001' },
      { name: 'Yala', postal_code: '540001' },
    ],
  },
  {
    state: 'Delta',
    capital: 'Asaba',
    lgas: [
      { name: 'Aniocha North', postal_code: '320001' },
      { name: 'Aniocha South', postal_code: '320001' },
      { name: 'Bomadi', postal_code: '320001' },
      { name: 'Burutu', postal_code: '320001' },
      { name: 'Ethiope East', postal_code: '320001' },
      { name: 'Ethiope West', postal_code: '320001' },
      { name: 'Ika North East', postal_code: '320001' },
      { name: 'Ika South', postal_code: '320001' },
      { name: 'Isoko North', postal_code: '320001' },
      { name: 'Isoko South', postal_code: '320001' },
      { name: 'Ndokwa East', postal_code: '320001' },
      { name: 'Ndokwa West', postal_code: '320001' },
      { name: 'Okpe', postal_code: '320001' },
      { name: 'Oshimili North', postal_code: '320001' },
      { name: 'Oshimili South', postal_code: '320001' },
      { name: 'Patani', postal_code: '320001' },
      { name: 'Sapele', postal_code: '320001' },
      { name: 'Udu', postal_code: '320001' },
      { name: 'Ughelli North', postal_code: '320001' },
      { name: 'Ughelli South', postal_code: '320001' },
      { name: 'Ukwuani', postal_code: '320001' },
      { name: 'Uvwie', postal_code: '320001' },
      { name: 'Warri North', postal_code: '320001' },
      { name: 'Warri South', postal_code: '320001' },
      { name: 'Warri South West', postal_code: '320001' },
    ],
  },
  {
    state: 'Ebonyi',
    capital: 'Abakaliki',
    lgas: [
      { name: 'Abakaliki', postal_code: '480001' },
      { name: 'Afikpo North', postal_code: '480001' },
      { name: 'Afikpo South', postal_code: '480001' },
      { name: 'Ebonyi', postal_code: '480001' },
      { name: 'Ezza North', postal_code: '480001' },
      { name: 'Ezza South', postal_code: '480001' },
      { name: 'Ikwo', postal_code: '480001' },
      { name: 'Ishielu', postal_code: '480001' },
      { name: 'Ivo', postal_code: '480001' },
      { name: 'Izzi', postal_code: '480001' },
      { name: 'Ohaozara', postal_code: '480001' },
      { name: 'Ohaukwu', postal_code: '480001' },
      { name: 'Onicha', postal_code: '480001' },
    ],
  },
  {
    state: 'Edo',
    capital: 'Benin City',
    lgas: [
      { name: 'Akoko-Edo', postal_code: '300001' },
      { name: 'Egor', postal_code: '300001' },
      { name: 'Esan Central', postal_code: '300001' },
      { name: 'Esan North-East', postal_code: '300001' },
      { name: 'Esan South-East', postal_code: '300001' },
      { name: 'Esan West', postal_code: '300001' },
      { name: 'Etsako Central', postal_code: '300001' },
      { name: 'Etsako East', postal_code: '300001' },
      { name: 'Etsako West', postal_code: '300001' },
      { name: 'Igueben', postal_code: '300001' },
      { name: 'Ikpoba Okha', postal_code: '300001' },
      { name: 'Oredo', postal_code: '300001' },
      { name: 'Orhionmwon', postal_code: '300001' },
      { name: 'Ovia North-East', postal_code: '300001' },
      { name: 'Ovia South-West', postal_code: '300001' },
      { name: 'Owan East', postal_code: '300001' },
      { name: 'Owan West', postal_code: '300001' },
      { name: 'Uhunmwonde', postal_code: '300001' },
    ],
  },
  {
    state: 'Ekiti',
    capital: 'Ado Ekiti',
    lgas: [
      { name: 'Ado Ekiti', postal_code: '360001' },
      { name: 'Efon', postal_code: '360001' },
      { name: 'Ekiti East', postal_code: '360001' },
      { name: 'Ekiti South-West', postal_code: '360001' },
      { name: 'Ekiti West', postal_code: '360001' },
      { name: 'Emure', postal_code: '360001' },
      { name: 'Gbonyin', postal_code: '360001' },
      { name: 'Ido Osi', postal_code: '360001' },
      { name: 'Ijero', postal_code: '360001' },
      { name: 'Ikere', postal_code: '360001' },
      { name: 'Ikole', postal_code: '360001' },
      { name: 'Ilejemeje', postal_code: '360001' },
      { name: 'Irepodun/Ifelodun', postal_code: '360001' },
      { name: 'Ise/Orun', postal_code: '360001' },
      { name: 'Moba', postal_code: '360001' },
      { name: 'Oye', postal_code: '360001' },
    ],
  },
  {
    state: 'Enugu',
    capital: 'Enugu',
    lgas: [
      { name: 'Aninri', postal_code: '400001' },
      { name: 'Awgu', postal_code: '400001' },
      { name: 'Enugu East', postal_code: '400001' },
      { name: 'Enugu North', postal_code: '400001' },
      { name: 'Enugu South', postal_code: '400001' },
      { name: 'Ezeagu', postal_code: '400001' },
      { name: 'Igbo Etiti', postal_code: '400001' },
      { name: 'Igbo Eze North', postal_code: '400001' },
      { name: 'Igbo Eze South', postal_code: '400001' },
      { name: 'Isi Uzo', postal_code: '400001' },
      { name: 'Nkanu East', postal_code: '400001' },
      { name: 'Nkanu West', postal_code: '400001' },
      { name: 'Nsukka', postal_code: '400001' },
      { name: 'Oji River', postal_code: '400001' },
      { name: 'Udenu', postal_code: '400001' },
      { name: 'Udi', postal_code: '400001' },
      { name: 'Uzo Uwani', postal_code: '400001' },
    ],
  },
  {
    state: 'FCT',
    capital: 'Abuja',
    lgas: [
      { name: 'Abaji', postal_code: '900001' },
      { name: 'Bwari', postal_code: '900001' },
      { name: 'Gwagwalada', postal_code: '900001' },
      { name: 'Kuje', postal_code: '900001' },
      { name: 'Kwali', postal_code: '900001' },
      { name: 'Municipal Area Council', postal_code: '900001' },
    ],
  },
  {
    state: 'Gombe',
    capital: 'Gombe',
    lgas: [
      { name: 'Akko', postal_code: '760001' },
      { name: 'Balanga', postal_code: '760001' },
      { name: 'Billiri', postal_code: '760001' },
      { name: 'Dukku', postal_code: '760001' },
      { name: 'Funakaye', postal_code: '760001' },
      { name: 'Gombe', postal_code: '760001' },
      { name: 'Kaltungo', postal_code: '760001' },
      { name: 'Kwami', postal_code: '760001' },
      { name: 'Nafada', postal_code: '760001' },
      { name: 'Shongom', postal_code: '760001' },
      { name: 'Yamaltu/Deba', postal_code: '760001' },
    ],
  },
  {
    state: 'Imo',
    capital: 'Owerri',
    lgas: [
      { name: 'Aboh Mbaise', postal_code: '460001' },
      { name: 'Ahiazu Mbaise', postal_code: '460001' },
      { name: 'Ehime Mbano', postal_code: '460001' },
      { name: 'Ezinihitte', postal_code: '460001' },
      { name: 'Ideato North', postal_code: '460001' },
      { name: 'Ideato South', postal_code: '460001' },
      { name: 'Ihitte/Uboma', postal_code: '460001' },
      { name: 'Ikeduru', postal_code: '460001' },
      { name: 'Isiala Mbano', postal_code: '460001' },
      { name: 'Isu', postal_code: '460001' },
      { name: 'Mbaitoli', postal_code: '460001' },
      { name: 'Ngor Okpala', postal_code: '460001' },
      { name: 'Njaba', postal_code: '460001' },
      { name: 'Nkwerre', postal_code: '460001' },
      { name: 'Nwangele', postal_code: '460001' },
      { name: 'Obowo', postal_code: '460001' },
      { name: 'Oguta', postal_code: '460001' },
      { name: 'Ohaji/Egbema', postal_code: '460001' },
      { name: 'Okigwe', postal_code: '460001' },
      { name: 'Orlu', postal_code: '460001' },
      { name: 'Orsu', postal_code: '460001' },
      { name: 'Oru East', postal_code: '460001' },
      { name: 'Oru West', postal_code: '460001' },
      { name: 'Owerri Municipal', postal_code: '460001' },
      { name: 'Owerri North', postal_code: '460001' },
      { name: 'Owerri West', postal_code: '460001' },
      { name: 'Unuimo', postal_code: '460001' },
    ],
  },
  {
    state: 'Jigawa',
    capital: 'Dutse',
    lgas: [
      { name: 'Auyo', postal_code: '720001' },
      { name: 'Babura', postal_code: '720001' },
      { name: 'Biriniwa', postal_code: '720001' },
      { name: 'Birnin Kudu', postal_code: '720001' },
      { name: 'Buji', postal_code: '720001' },
      { name: 'Dutse', postal_code: '720001' },
      { name: 'Gagarawa', postal_code: '720001' },
      { name: 'Garki', postal_code: '720001' },
      { name: 'Gumel', postal_code: '720001' },
      { name: 'Guri', postal_code: '720001' },
      { name: 'Gwaram', postal_code: '720001' },
      { name: 'Gwiwa', postal_code: '720001' },
      { name: 'Hadejia', postal_code: '720001' },
      { name: 'Jahun', postal_code: '720001' },
      { name: 'Kafin Hausa', postal_code: '720001' },
      { name: 'Kaugama', postal_code: '720001' },
      { name: 'Kazaure', postal_code: '720001' },
      { name: 'Kiri Kasama', postal_code: '720001' },
      { name: 'Kiyawa', postal_code: '720001' },
      { name: 'Maigatari', postal_code: '720001' },
      { name: 'Malam Madori', postal_code: '720001' },
      { name: 'Miga', postal_code: '720001' },
      { name: 'Ringim', postal_code: '720001' },
      { name: 'Roni', postal_code: '720001' },
      { name: 'Sule Tankarkar', postal_code: '720001' },
      { name: 'Taura', postal_code: '720001' },
      { name: 'Yankwashi', postal_code: '720001' },
    ],
  },
  {
    state: 'Kaduna',
    capital: 'Kaduna',
    lgas: [
      { name: 'Birnin Gwari', postal_code: '800001' },
      { name: 'Chikun', postal_code: '800001' },
      { name: 'Giwa', postal_code: '800001' },
      { name: 'Igabi', postal_code: '800001' },
      { name: 'Ikara', postal_code: '800001' },
      { name: 'Jaba', postal_code: '800001' },
      { name: "Jema'a", postal_code: '800001' },
      { name: 'Kachia', postal_code: '800001' },
      { name: 'Kaduna North', postal_code: '800001' },
      { name: 'Kaduna South', postal_code: '800001' },
      { name: 'Kagarko', postal_code: '800001' },
      { name: 'Kajuru', postal_code: '800001' },
      { name: 'Kaura', postal_code: '800001' },
      { name: 'Kauru', postal_code: '800001' },
      { name: 'Kubau', postal_code: '800001' },
      { name: 'Kudan', postal_code: '800001' },
      { name: 'Lere', postal_code: '800001' },
      { name: 'Makarfi', postal_code: '800001' },
      { name: 'Sabon Gari', postal_code: '800001' },
      { name: 'Sanga', postal_code: '800001' },
      { name: 'Soba', postal_code: '800001' },
      { name: 'Zangon Kataf', postal_code: '800001' },
      { name: 'Zaria', postal_code: '800001' },
    ],
  },
  {
    state: 'Kano',
    capital: 'Kano',
    lgas: [
      { name: 'Ajingi', postal_code: '700001' },
      { name: 'Albasu', postal_code: '700001' },
      { name: 'Bagwai', postal_code: '700001' },
      { name: 'Bebeji', postal_code: '700001' },
      { name: 'Bichi', postal_code: '700001' },
      { name: 'Bunkure', postal_code: '700001' },
      { name: 'Dala', postal_code: '700001' },
      { name: 'Dambatta', postal_code: '700001' },
      { name: 'Dawakin Kudu', postal_code: '700001' },
      { name: 'Dawakin Tofa', postal_code: '700001' },
      { name: 'Doguwa', postal_code: '700001' },
      { name: 'Fagge', postal_code: '700001' },
      { name: 'Gabasawa', postal_code: '700001' },
      { name: 'Garko', postal_code: '700001' },
      { name: 'Garun Mallam', postal_code: '700001' },
      { name: 'Gaya', postal_code: '700001' },
      { name: 'Gezawa', postal_code: '700001' },
      { name: 'Gwale', postal_code: '700001' },
      { name: 'Gwarzo', postal_code: '700001' },
      { name: 'Kabo', postal_code: '700001' },
      { name: 'Kano Municipal', postal_code: '700001' },
      { name: 'Karaye', postal_code: '700001' },
      { name: 'Kibiya', postal_code: '700001' },
      { name: 'Kiru', postal_code: '700001' },
      { name: 'Kumbotso', postal_code: '700001' },
      { name: 'Kunchi', postal_code: '700001' },
      { name: 'Kura', postal_code: '700001' },
      { name: 'Madobi', postal_code: '700001' },
      { name: 'Makoda', postal_code: '700001' },
      { name: 'Minjibir', postal_code: '700001' },
      { name: 'Nasarawa', postal_code: '700001' },
      { name: 'Rano', postal_code: '700001' },
      { name: 'Rimin Gado', postal_code: '700001' },
      { name: 'Rogo', postal_code: '700001' },
      { name: 'Shanono', postal_code: '700001' },
      { name: 'Sumaila', postal_code: '700001' },
      { name: 'Takai', postal_code: '700001' },
      { name: 'Tarauni', postal_code: '700001' },
      { name: 'Tofa', postal_code: '700001' },
      { name: 'Tsanyawa', postal_code: '700001' },
      { name: 'Tudun Wada', postal_code: '700001' },
      { name: 'Ungogo', postal_code: '700001' },
      { name: 'Warawa', postal_code: '700001' },
      { name: 'Wudil', postal_code: '700001' },
    ],
  },
  {
    state: 'Katsina',
    capital: 'Katsina',
    lgas: [
      { name: 'Bakori', postal_code: '820001' },
      { name: 'Batagarawa', postal_code: '820001' },
      { name: 'Batsari', postal_code: '820001' },
      { name: 'Baure', postal_code: '820001' },
      { name: 'Bindawa', postal_code: '820001' },
      { name: 'Charanchi', postal_code: '820001' },
      { name: 'Dandume', postal_code: '820001' },
      { name: 'Danja', postal_code: '820001' },
      { name: 'Dan Musa', postal_code: '820001' },
      { name: 'Daura', postal_code: '820001' },
      { name: 'Dutsi', postal_code: '820001' },
      { name: 'Dutsin Ma', postal_code: '820001' },
      { name: 'Faskari', postal_code: '820001' },
      { name: 'Funtua', postal_code: '820001' },
      { name: 'Ingawa', postal_code: '820001' },
      { name: 'Jibia', postal_code: '820001' },
      { name: 'Kafur', postal_code: '820001' },
      { name: 'Kaita', postal_code: '820001' },
      { name: 'Kankara', postal_code: '820001' },
      { name: 'Kankia', postal_code: '820001' },
      { name: 'Katsina', postal_code: '820001' },
      { name: 'Kurfi', postal_code: '820001' },
      { name: 'Kusada', postal_code: '820001' },
      { name: "Mai'Adua", postal_code: '820001' },
      { name: 'Malumfashi', postal_code: '820001' },
      { name: 'Mani', postal_code: '820001' },
      { name: 'Mashi', postal_code: '820001' },
      { name: 'Matazu', postal_code: '820001' },
      { name: 'Musawa', postal_code: '820001' },
      { name: 'Rimi', postal_code: '820001' },
      { name: 'Sabuwa', postal_code: '820001' },
      { name: 'Safana', postal_code: '820001' },
      { name: 'Sandamu', postal_code: '820001' },
      { name: 'Zango', postal_code: '820001' },
    ],
  },
  {
    state: 'Kebbi',
    capital: 'Birnin Kebbi',
    lgas: [
      { name: 'Aleiro', postal_code: '860001' },
      { name: 'Arewa Dandi', postal_code: '860001' },
      { name: 'Argungu', postal_code: '860001' },
      { name: 'Augie', postal_code: '860001' },
      { name: 'Bagudo', postal_code: '860001' },
      { name: 'Birnin Kebbi', postal_code: '860001' },
      { name: 'Bunza', postal_code: '860001' },
      { name: 'Dandi', postal_code: '860001' },
      { name: 'Fakai', postal_code: '860001' },
      { name: 'Gwandu', postal_code: '860001' },
      { name: 'Jega', postal_code: '860001' },
      { name: 'Kalgo', postal_code: '860001' },
      { name: 'Koko/Besse', postal_code: '860001' },
      { name: 'Maiyama', postal_code: '860001' },
      { name: 'Ngaski', postal_code: '860001' },
      { name: 'Sakaba', postal_code: '860001' },
      { name: 'Shanga', postal_code: '860001' },
      { name: 'Suru', postal_code: '860001' },
      { name: 'Wasagu/Danko', postal_code: '860001' },
      { name: 'Yauri', postal_code: '860001' },
      { name: 'Zuru', postal_code: '860001' },
    ],
  },
  {
    state: 'Kogi',
    capital: 'Lokoja',
    lgas: [
      { name: 'Adavi', postal_code: '260001' },
      { name: 'Ajaokuta', postal_code: '260001' },
      { name: 'Ankpa', postal_code: '260001' },
      { name: 'Bassa', postal_code: '260001' },
      { name: 'Dekina', postal_code: '260001' },
      { name: 'Ibaji', postal_code: '260001' },
      { name: 'Idah', postal_code: '260001' },
      { name: 'Igalamela Odolu', postal_code: '260001' },
      { name: 'Ijumu', postal_code: '260001' },
      { name: 'Kabba/Bunu', postal_code: '260001' },
      { name: 'Kogi', postal_code: '260001' },
      { name: 'Lokoja', postal_code: '260001' },
      { name: 'Mopa Muro', postal_code: '260001' },
      { name: 'Ofu', postal_code: '260001' },
      { name: 'Ogori/Magongo', postal_code: '260001' },
      { name: 'Okehi', postal_code: '260001' },
      { name: 'Okene', postal_code: '260001' },
      { name: 'Olamaboro', postal_code: '260001' },
      { name: 'Omala', postal_code: '260001' },
      { name: 'Yagba East', postal_code: '260001' },
      { name: 'Yagba West', postal_code: '260001' },
    ],
  },
  {
    state: 'Kwara',
    capital: 'Ilorin',
    lgas: [
      { name: 'Asa', postal_code: '240001' },
      { name: 'Baruten', postal_code: '240001' },
      { name: 'Edu', postal_code: '240001' },
      { name: 'Ekiti', postal_code: '240001' },
      { name: 'Ifelodun', postal_code: '240001' },
      { name: 'Ilorin East', postal_code: '240001' },
      { name: 'Ilorin South', postal_code: '240001' },
      { name: 'Ilorin West', postal_code: '240001' },
      { name: 'Irepodun', postal_code: '240001' },
      { name: 'Isin', postal_code: '240001' },
      { name: 'Kaiama', postal_code: '240001' },
      { name: 'Moro', postal_code: '240001' },
      { name: 'Offa', postal_code: '240001' },
      { name: 'Oke Ero', postal_code: '240001' },
      { name: 'Oyun', postal_code: '240001' },
      { name: 'Pategi', postal_code: '240001' },
    ],
  },
  {
    state: 'Lagos',
    capital: 'Ikeja',
    lgas: [
      { name: 'Agege', postal_code: '100001' },
      { name: 'Ajeromi-Ifelodun', postal_code: '100001' },
      { name: 'Alimosho', postal_code: '100001' },
      { name: 'Amuwo-Odofin', postal_code: '100001' },
      { name: 'Apapa', postal_code: '100001' },
      { name: 'Badagry', postal_code: '100001' },
      { name: 'Epe', postal_code: '100001' },
      { name: 'Eti Osa', postal_code: '101001' },
      { name: 'Ibeju-Lekki', postal_code: '100001' },
      { name: 'Ifako-Ijaiye', postal_code: '100001' },
      { name: 'Ikeja', postal_code: '100001' },
      { name: 'Ikorodu', postal_code: '100001' },
      { name: 'Kosofe', postal_code: '100001' },
      { name: 'Lagos Island', postal_code: '101001' },
      { name: 'Lagos Mainland', postal_code: '100001' },
      { name: 'Mushin', postal_code: '100001' },
      { name: 'Ojo', postal_code: '100001' },
      { name: 'Oshodi-Isolo', postal_code: '100001' },
      { name: 'Shomolu', postal_code: '100001' },
      { name: 'Surulere', postal_code: '100001' },
    ],
  },
  {
    state: 'Nasarawa',
    capital: 'Lafia',
    lgas: [
      { name: 'Akwanga', postal_code: '962001' },
      { name: 'Awe', postal_code: '962001' },
      { name: 'Doma', postal_code: '962001' },
      { name: 'Karu', postal_code: '962001' },
      { name: 'Keana', postal_code: '962001' },
      { name: 'Keffi', postal_code: '962001' },
      { name: 'Kokona', postal_code: '962001' },
      { name: 'Lafia', postal_code: '962001' },
      { name: 'Nasarawa', postal_code: '962001' },
      { name: 'Nasarawa Egon', postal_code: '962001' },
      { name: 'Obi', postal_code: '962001' },
      { name: 'Toto', postal_code: '962001' },
      { name: 'Wamba', postal_code: '962001' },
    ],
  },
  {
    state: 'Niger',
    capital: 'Minna',
    lgas: [
      { name: 'Agaie', postal_code: '920001' },
      { name: 'Agwara', postal_code: '920001' },
      { name: 'Bida', postal_code: '920001' },
      { name: 'Borgu', postal_code: '920001' },
      { name: 'Bosso', postal_code: '920001' },
      { name: 'Chanchaga', postal_code: '920001' },
      { name: 'Edati', postal_code: '920001' },
      { name: 'Gbako', postal_code: '920001' },
      { name: 'Gurara', postal_code: '920001' },
      { name: 'Katcha', postal_code: '920001' },
      { name: 'Kontagora', postal_code: '920001' },
      { name: 'Lapai', postal_code: '920001' },
      { name: 'Lavun', postal_code: '920001' },
      { name: 'Magama', postal_code: '920001' },
      { name: 'Mariga', postal_code: '920001' },
      { name: 'Mashegu', postal_code: '920001' },
      { name: 'Mokwa', postal_code: '920001' },
      { name: 'Moya', postal_code: '920001' },
      { name: 'Paikoro', postal_code: '920001' },
      { name: 'Rafi', postal_code: '920001' },
      { name: 'Rijau', postal_code: '920001' },
      { name: 'Shiroro', postal_code: '920001' },
      { name: 'Suleja', postal_code: '920001' },
      { name: 'Tafa', postal_code: '920001' },
      { name: 'Wushishi', postal_code: '920001' },
    ],
  },
  {
    state: 'Ogun',
    capital: 'Abeokuta',
    lgas: [
      { name: 'Abeokuta North', postal_code: '110001' },
      { name: 'Abeokuta South', postal_code: '110001' },
      { name: 'Ado-Odo/Ota', postal_code: '110001' },
      { name: 'Ewekoro', postal_code: '110001' },
      { name: 'Ifo', postal_code: '110001' },
      { name: 'Ijebu East', postal_code: '110001' },
      { name: 'Ijebu North', postal_code: '110001' },
      { name: 'Ijebu North East', postal_code: '110001' },
      { name: 'Ijebu Ode', postal_code: '110001' },
      { name: 'Ikenne', postal_code: '110001' },
      { name: 'Imeko Afon', postal_code: '110001' },
      { name: 'Ipokia', postal_code: '110001' },
      { name: 'Obafemi Owode', postal_code: '110001' },
      { name: 'Odeda', postal_code: '110001' },
      { name: 'Odogbolu', postal_code: '110001' },
      { name: 'Ogun Waterside', postal_code: '110001' },
      { name: 'Remo North', postal_code: '110001' },
      { name: 'Shagamu', postal_code: '110001' },
      { name: 'Yewa North', postal_code: '110001' },
      { name: 'Yewa South', postal_code: '110001' },
    ],
  },
  {
    state: 'Ondo',
    capital: 'Akure',
    lgas: [
      { name: 'Akoko North-East', postal_code: '340001' },
      { name: 'Akoko North-West', postal_code: '340001' },
      { name: 'Akoko South-East', postal_code: '340001' },
      { name: 'Akoko South-West', postal_code: '340001' },
      { name: 'Akure North', postal_code: '340001' },
      { name: 'Akure South', postal_code: '340001' },
      { name: 'Ese Odo', postal_code: '340001' },
      { name: 'Idanre', postal_code: '340001' },
      { name: 'Ifedore', postal_code: '340001' },
      { name: 'Ilaje', postal_code: '340001' },
      { name: 'Ile Oluji/Okeigbo', postal_code: '340001' },
      { name: 'Irele', postal_code: '340001' },
      { name: 'Odigbo', postal_code: '340001' },
      { name: 'Okitipupa', postal_code: '340001' },
      { name: 'Ondo East', postal_code: '340001' },
      { name: 'Ondo West', postal_code: '340001' },
      { name: 'Ose', postal_code: '340001' },
      { name: 'Owo', postal_code: '340001' },
    ],
  },
  {
    state: 'Osun',
    capital: 'Osogbo',
    lgas: [
      { name: 'Atakunmosa East', postal_code: '230001' },
      { name: 'Atakunmosa West', postal_code: '230001' },
      { name: 'Aiyedaade', postal_code: '230001' },
      { name: 'Aiyedire', postal_code: '230001' },
      { name: 'Boluwaduro', postal_code: '230001' },
      { name: 'Boripe', postal_code: '230001' },
      { name: 'Ede North', postal_code: '230001' },
      { name: 'Ede South', postal_code: '230001' },
      { name: 'Egbedore', postal_code: '230001' },
      { name: 'Ejigbo', postal_code: '230001' },
      { name: 'Ife Central', postal_code: '230001' },
      { name: 'Ife East', postal_code: '230001' },
      { name: 'Ife North', postal_code: '230001' },
      { name: 'Ife South', postal_code: '230001' },
      { name: 'Ifedayo', postal_code: '230001' },
      { name: 'Ifelodun', postal_code: '230001' },
      { name: 'Ila', postal_code: '230001' },
      { name: 'Ilesa East', postal_code: '230001' },
      { name: 'Ilesa West', postal_code: '230001' },
      { name: 'Irepodun', postal_code: '230001' },
      { name: 'Irewole', postal_code: '230001' },
      { name: 'Isokan', postal_code: '230001' },
      { name: 'Iwo', postal_code: '230001' },
      { name: 'Obokun', postal_code: '230001' },
      { name: 'Odo Otin', postal_code: '230001' },
      { name: 'Ola Oluwa', postal_code: '230001' },
      { name: 'Olorunda', postal_code: '230001' },
      { name: 'Oriade', postal_code: '230001' },
      { name: 'Orolu', postal_code: '230001' },
      { name: 'Osogbo', postal_code: '230001' },
    ],
  },
  {
    state: 'Oyo',
    capital: 'Ibadan',
    lgas: [
      { name: 'Afijio', postal_code: '200001' },
      { name: 'Akinyele', postal_code: '200001' },
      { name: 'Atiba', postal_code: '200001' },
      { name: 'Atisbo', postal_code: '200001' },
      { name: 'Egbeda', postal_code: '200001' },
      { name: 'Ibadan North', postal_code: '200001' },
      { name: 'Ibadan North-East', postal_code: '200001' },
      { name: 'Ibadan North-West', postal_code: '200001' },
      { name: 'Ibadan South-East', postal_code: '200001' },
      { name: 'Ibadan South-West', postal_code: '200001' },
      { name: 'Ibarapa Central', postal_code: '200001' },
      { name: 'Ibarapa East', postal_code: '200001' },
      { name: 'Ibarapa North', postal_code: '200001' },
      { name: 'Ido', postal_code: '200001' },
      { name: 'Irepo', postal_code: '200001' },
      { name: 'Iseyin', postal_code: '200001' },
      { name: 'Itesiwaju', postal_code: '200001' },
      { name: 'Iwajowa', postal_code: '200001' },
      { name: 'Kajola', postal_code: '200001' },
      { name: 'Lagelu', postal_code: '200001' },
      { name: 'Ogbomosho North', postal_code: '200001' },
      { name: 'Ogbomosho South', postal_code: '200001' },
      { name: 'Ogo Oluwa', postal_code: '200001' },
      { name: 'Olorunsogo', postal_code: '200001' },
      { name: 'Oluyole', postal_code: '200001' },
      { name: 'Ona Ara', postal_code: '200001' },
      { name: 'Oorelope', postal_code: '200001' },
      { name: 'Ori Ire', postal_code: '200001' },
      { name: 'Oyo East', postal_code: '200001' },
      { name: 'Oyo West', postal_code: '200001' },
      { name: 'Saki East', postal_code: '200001' },
      { name: 'Saki West', postal_code: '200001' },
      { name: 'Surulere', postal_code: '200001' },
    ],
  },
  {
    state: 'Plateau',
    capital: 'Jos',
    lgas: [
      { name: 'Barkin Ladi', postal_code: '930001' },
      { name: 'Bassa', postal_code: '930001' },
      { name: 'Bokkos', postal_code: '930001' },
      { name: 'Jos East', postal_code: '930001' },
      { name: 'Jos North', postal_code: '930001' },
      { name: 'Jos South', postal_code: '930001' },
      { name: 'Kanam', postal_code: '930001' },
      { name: 'Kanke', postal_code: '930001' },
      { name: 'Langtang North', postal_code: '930001' },
      { name: 'Langtang South', postal_code: '930001' },
      { name: 'Mangu', postal_code: '930001' },
      { name: 'Mikang', postal_code: '930001' },
      { name: 'Pankshin', postal_code: '930001' },
      { name: "Qua'an Pan", postal_code: '930001' },
      { name: 'Riyom', postal_code: '930001' },
      { name: 'Shendam', postal_code: '930001' },
      { name: 'Wase', postal_code: '930001' },
    ],
  },
  {
    state: 'Rivers',
    capital: 'Port Harcourt',
    lgas: [
      { name: 'Abua/Odual', postal_code: '500001' },
      { name: 'Ahoada East', postal_code: '500001' },
      { name: 'Ahoada West', postal_code: '500001' },
      { name: 'Akuku-Toru', postal_code: '500001' },
      { name: 'Andoni', postal_code: '500001' },
      { name: 'Asari-Toru', postal_code: '500001' },
      { name: 'Bonny', postal_code: '500001' },
      { name: 'Degema', postal_code: '500001' },
      { name: 'Eleme', postal_code: '500001' },
      { name: 'Emohua', postal_code: '500001' },
      { name: 'Etche', postal_code: '500001' },
      { name: 'Gokana', postal_code: '500001' },
      { name: 'Ikwerre', postal_code: '500001' },
      { name: 'Khana', postal_code: '500001' },
      { name: 'Obio/Akpor', postal_code: '500001' },
      { name: 'Ogba/Egbema/Ndoni', postal_code: '500001' },
      { name: 'Ogu/Bolo', postal_code: '500001' },
      { name: 'Okrika', postal_code: '500001' },
      { name: 'Omuma', postal_code: '500001' },
      { name: 'Opobo/Nkoro', postal_code: '500001' },
      { name: 'Oyigbo', postal_code: '500001' },
      { name: 'Port Harcourt', postal_code: '500001' },
      { name: 'Tai', postal_code: '500001' },
    ],
  },
  {
    state: 'Sokoto',
    capital: 'Sokoto',
    lgas: [
      { name: 'Binji', postal_code: '840001' },
      { name: 'Bodinga', postal_code: '840001' },
      { name: 'Dange Shuni', postal_code: '840001' },
      { name: 'Gada', postal_code: '840001' },
      { name: 'Goronyo', postal_code: '840001' },
      { name: 'Gudu', postal_code: '840001' },
      { name: 'Gwadabawa', postal_code: '840001' },
      { name: 'Illela', postal_code: '840001' },
      { name: 'Isa', postal_code: '840001' },
      { name: 'Kebbe', postal_code: '840001' },
      { name: 'Kware', postal_code: '840001' },
      { name: 'Rabah', postal_code: '840001' },
      { name: 'Sabon Birni', postal_code: '840001' },
      { name: 'Shagari', postal_code: '840001' },
      { name: 'Silame', postal_code: '840001' },
      { name: 'Sokoto North', postal_code: '840001' },
      { name: 'Sokoto South', postal_code: '840001' },
      { name: 'Tambuwal', postal_code: '840001' },
      { name: 'Tangaza', postal_code: '840001' },
      { name: 'Tureta', postal_code: '840001' },
      { name: 'Wamako', postal_code: '840001' },
      { name: 'Wurno', postal_code: '840001' },
      { name: 'Yabo', postal_code: '840001' },
    ],
  },
  {
    state: 'Taraba',
    capital: 'Jalingo',
    lgas: [
      { name: 'Ardo Kola', postal_code: '660001' },
      { name: 'Bali', postal_code: '660001' },
      { name: 'Donga', postal_code: '660001' },
      { name: 'Gashaka', postal_code: '660001' },
      { name: 'Gassol', postal_code: '660001' },
      { name: 'Ibi', postal_code: '660001' },
      { name: 'Jalingo', postal_code: '660001' },
      { name: 'Karim Lamido', postal_code: '660001' },
      { name: 'Kurmi', postal_code: '660001' },
      { name: 'Lau', postal_code: '660001' },
      { name: 'Sardauna', postal_code: '660001' },
      { name: 'Takum', postal_code: '660001' },
      { name: 'Ussa', postal_code: '660001' },
      { name: 'Wukari', postal_code: '660001' },
      { name: 'Yorro', postal_code: '660001' },
      { name: 'Zing', postal_code: '660001' },
    ],
  },
  {
    state: 'Yobe',
    capital: 'Damaturu',
    lgas: [
      { name: 'Bade', postal_code: '620001' },
      { name: 'Bursari', postal_code: '620001' },
      { name: 'Damaturu', postal_code: '620001' },
      { name: 'Fika', postal_code: '620001' },
      { name: 'Fune', postal_code: '620001' },
      { name: 'Geidam', postal_code: '620001' },
      { name: 'Gujba', postal_code: '620001' },
      { name: 'Gulani', postal_code: '620001' },
      { name: 'Jakusko', postal_code: '620001' },
      { name: 'Karasuwa', postal_code: '620001' },
      { name: 'Machina', postal_code: '620001' },
      { name: 'Nangere', postal_code: '620001' },
      { name: 'Nguru', postal_code: '620001' },
      { name: 'Potiskum', postal_code: '620001' },
      { name: 'Tarmuwa', postal_code: '620001' },
      { name: 'Yunusari', postal_code: '620001' },
      { name: 'Yusufari', postal_code: '620001' },
    ],
  },
  {
    state: 'Zamfara',
    capital: 'Gusau',
    lgas: [
      { name: 'Anka', postal_code: '880001' },
      { name: 'Bakura', postal_code: '880001' },
      { name: 'Birnin Magaji/Kiyaw', postal_code: '880001' },
      { name: 'Bukkuyum', postal_code: '880001' },
      { name: 'Bungudu', postal_code: '880001' },
      { name: 'Gummi', postal_code: '880001' },
      { name: 'Gusau', postal_code: '880001' },
      { name: 'Kaura Namoda', postal_code: '880001' },
      { name: 'Maradun', postal_code: '880001' },
      { name: 'Maru', postal_code: '880001' },
      { name: 'Shinkafi', postal_code: '880001' },
      { name: 'Talata Mafara', postal_code: '880001' },
      { name: 'Tsafe', postal_code: '880001' },
      { name: 'Zurmi', postal_code: '880001' },
    ],
  },
];

export const NIGERIAN_BANKS = [
  { name: '5TT MFB', code: 'H14' },
  { name: '78 FINANCE COMPANY LIMITED', code: 'F39' },
  { name: '9 PAYMENT SERVICE BANK', code: 'C34' },
  { name: '9JAPAY MICROFINANCE BANK', code: 'EO9' },
  { name: 'ABBEY MORTGAGE BANK', code: 'A04' },
  { name: 'ABSU MICROFINANCE BANK', code: 'F12' },
  { name: 'ABU MICROFINANCE BANK', code: '780' },
  { name: 'ABUCOOP MICROFINANCE BANK', code: 'D80' },
  { name: 'ACCESS BANK NIGERIA PLC', code: '044' },
  { name: 'ACCESS BANK PLC (DIAMOND)', code: '063' },
  { name: 'ACCESS MOBILE', code: '323' },
  { name: 'ACCESS YELLO & BETA', code: 'B77' },
  { name: 'ACCION MICROFINANCE BANK', code: '603' },
  { name: 'ADA MFB', code: 'F84' },
  { name: 'ADAMAWA MORTGAGE BANK', code: 'H04' },
  { name: 'ADDOSSER MICROFINANCE BANK', code: 'A07' },
  { name: 'ADVANCLY MFB', code: 'E41' },
  { name: 'AELLA MFB', code: 'E05' },
  { name: 'AFEKHAFE MICROFINANCE BANK', code: '716' },
  { name: 'AFRIBANK NIGERIA PLC', code: '014' },
  { name: 'AG MORTGAGE BANK PLC', code: 'A09' },
  { name: 'AGOSASA MICROFINANCE BANK', code: 'D91' },
  { name: 'AKALABO MFB', code: 'D97' },
  { name: 'AKPO MICROFINANCE BANK', code: '965' },
  { name: 'AKSU MFB', code: 'E31' },
  { name: 'AKU MICROFINANCE BANK', code: 'D25' },
  { name: 'AKWA SAVINGS AND LOANS LIMITED', code: 'C73' },
  { name: 'AL-BARAKAH MICROFINANCE BANK', code: 'A11' },
  { name: 'ALERT MICROFINANCE BANK', code: 'A13' },
  { name: 'ALPHA MORGAN BANK', code: 'E52' },
  { name: 'ALTERNATIVE BANK LIMITED', code: 'F25' },
  { name: 'ALVANA MICROFINANCE BANK', code: '751' },
  { name: 'AMEGY MICROFINANCE BANK', code: 'E09' },
  { name: 'AMOYE MICROFINANCE BANK', code: '964' },
  { name: 'AMPLE MFB', code: 'E45' },
  { name: 'ANIOCHA MICROFINANCE BANK', code: '885' },
  { name: 'ANIOMA MFB', code: 'E26' },
  { name: 'APPLE MICROFINANCE BANK', code: 'A20' },
  { name: 'ARM MFB', code: 'E85' },
  { name: 'ASO SAVINGS AND LOANS', code: '785' },
  { name: 'ASSETS MICROFINANCE BANK', code: '712' },
  { name: 'ATBU MFB', code: 'D70' },
  { name: 'AUCHI POLY MFB', code: 'E87' },
  { name: 'AVE MARIA MICROFINANCE BANK', code: '970' },
  { name: 'AVUENEGBE MICROFINANCE BANK', code: '969' },
  { name: 'AWACASH MICROFINANCE BANK', code: '880' },
  { name: 'AWESOME MICROFINANCE BANK', code: 'F27' },
  { name: 'AZTEC MICROFINANCE BANK AMB', code: 'D18' },
  { name: 'BABURA MICROFINANCE BANK', code: 'F02' },
  { name: 'BAINES CREDIT MICROFINANCE BANK', code: 'A25' },
  { name: 'BALOGUN FULANI MICROFINANCE BANK', code: '713' },
  { name: 'BAM MICROFINANCE BANK', code: 'F55' },
  { name: 'BANC CORP MICROFINANCE BANK', code: 'E04' },
  { name: 'BANK OF AGRICULTURE', code: 'H13' },
  { name: 'BANKIT MFB', code: 'A02' },
  { name: 'BAOBAB MFB', code: 'A27' },
  { name: 'BARNAWA MFB', code: 'E72' },
  { name: 'BELLBANK MICROFINANCE BANK', code: 'F63' },
  { name: 'BERACHAH MFB', code: 'F52' },
  { name: 'BESTSTAR MICROFINANCE BANK', code: '958' },
  { name: 'BETASTACK TECHNOLOGIES', code: 'H07' },
  { name: 'BETHEL MICROFINANCE BANK', code: 'F54' },
  { name: 'BIPC MICROFINANCE BANK', code: 'C14' },
  { name: 'BLOOMS MFB', code: 'E43' },
  { name: 'BLOOMS MFB', code: 'A43' },
  { name: 'BLUEPRINT INVESTMENTS MICROFINANCE BANK', code: '811' },
  { name: 'BOI MICROFINANCE BANK', code: 'D72' },
  { name: 'BOJI FMB', code: '796' },
  { name: 'BOKKOS MFB', code: 'F74' },
  { name: 'BOLD MFB', code: 'E27' },
  { name: 'BOOST MFB', code: 'H05' },
  { name: 'BORSTAL MICROFINANCE BANK', code: 'F13' },
  { name: 'BOWEN MICROFINANCE BANK', code: 'A32' },
  { name: 'BOWMAN MFB', code: 'E94' },
  { name: 'BRANCH INTERNATIONAL FINANCE COMPANY LIMITED', code: 'C78' },
  { name: 'BRENT MORTGAGE BANK', code: '615' },
  { name: 'BRIDGEWAY MICROFINANCE BANK', code: '335' },
  { name: 'BRIGHTWAY MICROFINANCE BANK', code: 'A35' },
  { name: 'BRIYTH-COVENANT MICROFINANCE BANK', code: '883' },
  { name: 'BUILD MICROFINANCE BANK', code: '889' },
  { name: 'BUNDI MICROFINANCE', code: 'F30' },
  { name: 'BUNKURE MICROFINANCE BANK', code: 'F20' },
  { name: 'BUYPOWER MICROFINANCE BANK', code: 'F57' },
  { name: 'CANAAN MICROFINANCE BANK', code: 'F16' },
  { name: 'CARBON', code: '565' },
  { name: 'CARDINALSTONE FINANCE', code: '890' },
  { name: 'CASHBRIDGE MICROFINANCE BANK', code: '886' },
  { name: 'CASHCONNECT', code: 'A36' },
  { name: 'CASHRITE MICROFINANCE BANK', code: 'F24' },
  { name: 'CEDAR MICROFINANCE BANK', code: '921' },
  { name: 'CEMCS MICROFINANCE BANK', code: 'A37' },
  { name: 'CENTRAL BANK OF NIGERIA', code: '010' },
  { name: 'CENTRUM FINANCE', code: 'E34' },
  { name: 'CHAMS MOBILE', code: 'B78' },
  { name: 'CHANELLE MICROFINANCE BANK', code: 'D87' },
  { name: 'CHARIS MFB', code: 'E97' },
  { name: 'CHIBUEZE MICROFINANCE BANK', code: '694' },
  { name: 'CHUKWUNENYE MFB', code: 'D50' },
  { name: 'CITIBANK', code: '023' },
  { name: 'CITYCODE MORTGAGE BANK', code: 'F45' },
  { name: 'CLEARPAY MICROFINANCE BANK', code: '731' },
  { name: 'COALCAMP MICROFINANCE BANK', code: '714' },
  { name: 'COASTLINE MICROFINANCE BANK', code: 'A40' },
  { name: 'CONFIDENCE MICROFINANCE BANK', code: 'D26' },
  { name: 'COOP MORTGAGE BANK', code: '693' },
  { name: 'COOPFUND MFB', code: 'F90' },
  { name: 'CORESTEP MICROFINANCE BANK', code: 'A43' },
  { name: 'CORONATION MERCHANT BANK', code: 'C16' },
  { name: 'COVENANT MICROFINANCE BANK', code: '756' },
  { name: 'CREDIT AFRIQUE MICROFINANCE BANK', code: 'A44' },
  { name: 'CREDITVILLE MICROFINANCE BANK', code: '904' },
  { name: 'CRUST MICROFINANCE BANK', code: 'C83' },
  { name: 'CRUTECH MICROFINANCE BANK', code: '802' },
  { name: 'CRYSTAL FINANCE COMPANY LIMITED', code: 'E10' },
  { name: 'CSD MICROFINANCE BANK', code: 'F66' },
  { name: 'DAILY TRUST MICROFINANCE BANK', code: 'F83' },
  { name: 'DAL MFB', code: '891' },
  { name: 'DAVENPORT MICROFINANCE BANK', code: 'F41' },
  { name: 'DAVODANI MICROFINANCE BANK', code: 'A45' },
  { name: 'DESTINY MFB', code: 'F97' },
  { name: 'DIGITVANT MFB', code: 'E22' },
  { name: 'DIGNITY FINANCE AND INVESTMENT LIMITED', code: '963' },
  { name: 'DILLON MFB', code: 'E98' },
  { name: 'DIOBU MICROFINANCE BANK', code: 'F05' },
  { name: 'DOJE MICROFINANCE BANK LIMITED', code: 'F43' },
  { name: 'DOT MICROFINANCE BANK', code: 'C84' },
  { name: 'DSC MICROFINANCE BANK', code: 'E84' },
  { name: 'DW MFB', code: 'E17' },
  { name: 'EARNWELL MICROFINANCE BANK', code: 'F42' },
  { name: 'EARTHOLEUM', code: '626' },
  { name: 'EASTMAN MFB', code: 'H01' },
  { name: 'EBSU MFB', code: 'D79' },
  { name: 'ECOBANK NIGERIA PLC', code: '050' },
  { name: 'ECOBANK XPRESS ACCOUNT', code: 'B81' },
  { name: 'EDFIN MICROFINANCE BANK', code: '645' },
  { name: 'E-FINANCE', code: '895' },
  { name: 'EJINDU MFB', code: 'F67' },
  { name: 'EK-RELIABLE MICROFINANCE BANK', code: 'A51' },
  { name: 'EMAAR MFB', code: 'F87' },
  { name: 'ENCO FINANCE COMPANY LTD', code: '972' },
  { name: 'ENTERPRISE BANK LIMITED', code: '084' },
  { name: 'ENTITY MICROFINANCE BANK', code: 'F33' },
  { name: 'EQUITORIAL TRUST BANK PLC', code: '040' },
  { name: 'ESAN MICROFINANCE BANK', code: 'A55' },
  { name: 'ESO-E MICROFINANCE BANK', code: 'A56' },
  { name: 'E-TRANZACT', code: '317' },
  { name: 'EVIB FINANCE', code: 'E71' },
  { name: 'EXCEL MICROFINANCE BANK', code: 'F49' },
  { name: 'FAIRMONEY MICROFINANCE BANK', code: 'D10' },
  { name: 'FAME MICROFINANCE BANK', code: 'D96' },
  { name: 'FBN MOBILE', code: '309' },
  { name: 'FBN MORTGAGE BANK (FIRST TRUST MORTGAGE BANK)', code: 'A70' },
  { name: 'FBNQUEST MERCHANT BANK', code: 'C17' },
  { name: 'FCMB EASY ACCOUNT', code: '312' },
  { name: 'FCMB MFB', code: 'F38' },
  { name: 'FEDERAL POLYTECHNIC NEKEDE MICROFINANCE BANK', code: 'F37' },
  { name: 'FETS', code: 'B85' },
  { name: 'FIDELITY BANK PLC', code: '070' },
  { name: 'FIDELITY MOBILE', code: 'B86' },
  { name: 'FIDFUND MICROFINANCE BANK', code: '568' },
  { name: 'FINCA MICROFINANCE BANK', code: 'C36' },
  { name: 'FIRMUS MICROFINANCE BANK', code: '676' },
  { name: 'FIRST ALLY MFB', code: '592' },
  { name: 'FIRST BANK PLC', code: '011' },
  { name: 'FIRST CITY MONUMENT BANK PLC', code: '214' },
  { name: 'FIRST INLAND BANK PLC', code: '085' },
  { name: 'FIRST MARINA TRUST FINANCE', code: 'E92' },
  { name: 'FLEXI MFB', code: 'H15' },
  { name: 'FOCUS MFB', code: 'F79' },
  { name: 'FORTIS MOBILE', code: 'B88' },
  { name: 'FORTRESS MICROFINANCE BANK', code: 'D53' },
  { name: 'FSDH', code: '501' },
  { name: 'FUD MFB', code: 'A61' },
  { name: 'GABASAWA MICROFINANCE BANK', code: '894' },
  { name: 'GADOL FINANCE', code: 'E68' },
  { name: 'GARUN MALLAM MFB', code: 'F72' },
  { name: 'GATEWAY MORTGAGE BANK', code: 'A73' },
  { name: 'GIDAUNIYAR ALHERI MICROFINANCE BANK', code: '902' },
  { name: 'GIREI MICROFINANCE BANK', code: '703' },
  { name: 'GLOBAL INITIATIVE MICROFINANCE BANK', code: '884' },
  { name: 'GLOBUS BANK', code: '103' },
  { name: 'GLORY MICROFIANCE BANK', code: 'A74' },
  { name: 'GOLDMAN MICROFINANCE BANK LIMITED', code: '078' },
  { name: 'GOMBE MICROFINANCE BANK LIMITED', code: 'F07' },
  { name: 'GOMONEY', code: 'B89' },
  { name: 'GOOD SHEPHERD MICROFINANCE BANK', code: 'F46' },
  { name: 'GOODNEWS MICROFINANCE', code: 'C85' },
  { name: 'GOSIFECHUKWU MFB', code: 'F60' },
  { name: 'GRANTS MICROFINANCE BANK', code: 'F36' },
  { name: 'GREENACRES MICROFINANCE BANK', code: 'F11' },
  { name: 'GREENVILLE MICROFINANCE BANK', code: 'A77' },
  { name: 'GREENWICH MERCHANT BANK', code: 'C57' },
  { name: 'GROOMING MICROFINANCE BANK', code: 'A78' },
  { name: 'GTBANK MOBILE MONEY', code: 'B90' },
  { name: 'GTBANK PLC', code: '058' },
  { name: 'GTI MICROFINANCE BANK', code: 'A79' },
  { name: 'GWONG MICROFINANCE BANK', code: 'F31' },
  { name: 'HAGGAI MORTGAGE BANK LIMITED', code: 'A81' },
  { name: 'HALO MICROFINANCE BANK', code: 'D19' },
  { name: 'HEDONMARK MOBILE', code: 'B91' },
  { name: 'HILLPOST MFB', code: 'E40' },
  { name: 'HOMEBASE MORTGAGE BANK', code: 'C74' },
  { name: 'HOPE PAYMENT SERVICE BANK', code: '800' },
  { name: 'IBANK MICROFINANCE BANK', code: '779' },
  { name: 'IBETO MICROFINANCE BANK', code: 'D75' },
  { name: 'IBOLO MICROFINANCE BANK', code: 'D24' },
  { name: 'IBU-AJE MICROFINANCE BANK', code: 'D51' },
  { name: 'IC-GLOBAL MFB', code: 'D33' },
  { name: 'IHIALA MFB', code: 'F95' },
  { name: 'IJARE MFB', code: 'D78' },
  { name: 'IKENNE MICROFINANCE BANK', code: 'A86' },
  { name: 'IKERE MFB', code: 'E73' },
  { name: 'IKIRE MICROFINANCE BANK', code: 'A87' },
  { name: 'IKOYI ILE MICROFINANCE BANK', code: 'F56' },
  { name: 'ILARO POLY MICROFINANCE BANK', code: 'C94' },
  { name: 'ILE-OLUJI MFB', code: 'F93' },
  { name: 'ILISAN MFB', code: 'F77' },
  { name: 'ILORA MICROFINANCE', code: 'F10' },
  { name: 'IMPERIAL HOMES MORTGAGE BANK', code: 'A89' },
  { name: 'IMSU MICROFINANCE BANK', code: 'F40' },
  { name: 'INDULGE MFB', code: 'E53' },
  { name: 'INFINITY TRUST MORTGAGE BANK', code: 'A91' },
  { name: 'INSIGHT MFB', code: 'F68' },
  { name: 'ISALE OYO MICROFINANCE BANK', code: 'A93' },
  { name: 'ISLAND MICROFINANCE BANK', code: '867' },
  { name: 'JAIZ BANK', code: '301' },
  { name: 'JESSEFIELD MICROFINANCE', code: 'D92' },
  { name: 'JIGAWA SAVINGS AND LOANS LIMITED', code: 'E12' },
  { name: 'JUBILEE LIFE MORTGAGE BANK', code: 'D92' },
  { name: 'KADUPE MICROFINANCE BANK', code: 'F34' },
  { name: 'KAIZEN MICROFINANCE BANK', code: 'E69' },
  { name: 'KANOPOLY MICROFINANCE BANK LIMITED', code: '971' },
  { name: 'KATAGUM MFB', code: 'D84' },
  { name: 'KATSU MFB', code: 'E48' },
  { name: 'KAYI MICROFINANCE BANK', code: 'F53' },
  { name: 'KEYSTONE BANK PLC', code: '082' },
  { name: 'KINGDOM COLLEGE MICROFINANCE BANK', code: 'D52' },
  { name: 'KKU MICROFINANCE BANK', code: '899' },
  { name: 'KOLOMONI MICROFINANCE BANK', code: '737' },
  { name: 'KONGA PAY', code: '025' },
  { name: 'KONTAGORA MICROFINANCE BANK', code: 'A97' },
  { name: 'KOPO KOPE MICROFINANCE BANK', code: '910' },
  { name: 'KREDI MONEY MICROFINANCE BANK LTD', code: '333' },
  { name: 'KUDA MICROFINANCE BANK', code: 'A98' },
  { name: 'LA FAYETTE MICROFINANCE BANK', code: '594' },
  { name: 'LAGOS BUILDING INVESTMENT COMPANY', code: 'C25' },
  { name: 'LAPO MICROFINANCE BANK', code: 'B01' },
  { name: 'LAWYERS MFB', code: 'F94' },
  { name: 'LEADCITY MICROFINANCE BANK', code: 'F17' },
  { name: 'LEGEND MICROFINANCE BANK', code: 'B03' },
  { name: 'LETSHEGO MFB', code: '216' },
  { name: 'LIGHTWAY MFB', code: 'E54' },
  { name: 'LINKS MICROFINANCE BANK', code: '699' },
  { name: 'LIVING TRUST MORTGAGE BANK', code: 'C38' },
  { name: 'LOBREM MICROFINANCE BANK', code: 'D21' },
  { name: 'LOMA MFB', code: '903' },
  { name: 'LOTUS BANK', code: '303' },
  { name: 'LUKEFIELD FINANCE COMPANY LIMITED', code: '897' },
  { name: 'MAAL MFB', code: 'E38' },
  { name: 'MAB ALLIANZ MICROFINANCE BANK', code: '900' },
  { name: 'MABINAS MICROFINANCE BANK', code: '879' },
  { name: 'MACROD MICROFINANCE BANK LIMITED', code: '906' },
  { name: 'MADOBI MICROFINANCE BANK', code: '893' },
  { name: 'MAESTRO MFB', code: 'E21' },
  { name: 'MANNY MICROFINANCE BANK', code: 'C86' },
  { name: 'MAYFAIR MICROFINANCE BANK', code: 'B09' },
  { name: 'MEDEF MICROFINANCE BANK', code: '962' },
  { name: 'MEGA MFB', code: 'H02' },
  { name: 'MEGAPRAISE MICROFINANCE BANK', code: 'E44' },
  { name: 'MGBIDI MICROFINANCE BANK', code: 'D28' },
  { name: 'MICHAEL OKPARA UNIAGRIC MICROFINANCE BANK', code: 'F23' },
  { name: 'MICROVIS MICROFINANCE BANK', code: 'B12' },
  { name: 'MIDLAND MICROFINANCE BANK', code: '766' },
  { name: 'MIMO (MKUDI)', code: 'B94' },
  { name: 'MINJIBIR MICROFINANCE BANK', code: '882' },
  { name: 'MINT-FINEX MFB', code: 'B13' },
  { name: 'MKOBO MFB', code: '826' },
  { name: 'MOLUSI MICROFINANCE BANK', code: 'B14' },
  { name: 'MOMO PAYMENT SERVICE BANK', code: 'C47' },
  { name: 'MONEYFIELD MICROFINANCE BANK', code: 'A39' },
  { name: 'MONEYMASTER PSB', code: 'C46' },
  { name: 'MONEYTRONICS MFB', code: 'E99' },
  { name: 'MONIEPOINT MICROFINANCE BANK', code: 'C39' },
  { name: 'MOREMONEE MICROFINANCE BANK LIMITED', code: 'F62' },
  { name: 'MUTUAL ALLIANCE MORTGAGE BANK', code: 'F59' },
  { name: 'MUTUAL BENEFITS MICROFINANCE BANK', code: 'B17' },
  { name: 'MUTUAL TRUST MICROFINANCE BANK', code: 'B18' },
  { name: 'NAGARTA MICROFINANCE BANK', code: '598' },
  { name: 'NASARAWA MICROFINANCE BANK', code: '807' },
  { name: 'NDDC MICROFINANCE BANK', code: 'F47' },
  { name: 'NEPTUNE MICROFINANCE BANK', code: 'B21' },
  { name: 'NET MFB', code: 'F58' },
  { name: 'NEXIM BANK', code: 'F18' },
  { name: 'NEXTON MICROFINANCE BANK', code: 'E79' },
  { name: 'NIBSS TEST BANK', code: '039_' },
  { name: 'NIRSAL MICROFINANCE BANK', code: 'B26' },
  { name: 'NOMASE MFB', code: 'E20' },
  { name: 'NOMBANK MFB', code: '953' },
  { name: 'NOUN MFB', code: 'E89' },
  { name: 'NOVA BANK', code: '561' },
  { name: 'NOWNOW DIGITAL SYSTEMS', code: '997' },
  { name: 'NPF MICROFINANCE BANK', code: 'B28' },
  { name: 'NSEHE MICROFINANCE BANK', code: '888' },
  { name: 'NUGGETS MFB', code: 'F69' },
  { name: 'NUMO MICORFINANCE BANK', code: '786' },
  { name: 'NURTURE MICROFINANCE BANK', code: '660' },
  { name: 'NWANNEGADI MICROFINANCE BANK', code: 'D86' },
  { name: 'OAKLAND MFB', code: '743' },
  { name: 'OBELEDU MFB', code: 'E33' },
  { name: 'OBOLLO MFB', code: 'E81' },
  { name: 'OCEANIC BANK NIGERIA PLC', code: '056' },
  { name: 'ODOAKPU MICROFINANCE BANK LIMITED', code: 'F19' },
  { name: 'OGBERURU MFB', code: 'E18' },
  { name: 'OHHA MICROFINANCE BANK', code: '887' },
  { name: 'OK MICROFINANCE BANK', code: 'C98' },
  { name: 'OKENGWE MICROFINANCE BANK', code: 'F14' },
  { name: 'OKO MFB', code: 'E32' },
  { name: 'OKWO-OHA MFB', code: 'E36' },
  { name: 'OLD SHOREHAM MFB', code: '690' },
  { name: 'OLIVE MFB', code: 'F71' },
  { name: 'OLOFIN-OWENA MICROFINANCE BANK', code: 'D61' },
  { name: 'OLUCHUKWU MICROFINANCE BANK', code: 'D60' },
  { name: 'OMAK MFB', code: 'F76' },
  { name: 'OPAY', code: 'C03' },
  { name: 'OPTIMUS BANK LIMITED', code: '107' },
  { name: 'OSANTA MFB', code: 'E28' },
  { name: 'OSOMHE MFB', code: 'D98' },
  { name: 'OSPOLY MICROFINANCE BANK', code: 'F44' },
  { name: 'OURS MFB', code: 'E70' },
  { name: 'OYAN MICROFINANCE BANK', code: '881' },
  { name: 'PAGA', code: 'B98' },
  { name: 'PAGE MFBANK', code: 'B35' },
  { name: 'PALMPAY LIMITED', code: 'B99' },
  { name: 'PARALLEX BANK LIMITED', code: '104' },
  { name: 'PARKWAY', code: 'D89' },
  { name: 'PARRALLLLEX', code: '526' },
  { name: 'PATHFINDER MICROFINANCE BANK LIMITED', code: 'F51' },
  { name: 'PAYATTITUDE ONLINE', code: 'C02' },
  { name: 'PAYSTACK-TITAN', code: 'C70' },
  { name: 'PEACE MICROFINANCE BANK', code: 'C40' },
  { name: 'PECANTRUST MICROFINANCE BANK', code: 'B37' },
  { name: 'PENIEL MICROFINANCE BANK', code: 'D90' },
  { name: 'PENNYWISE MFB', code: 'B38' },
  { name: 'PETTYSAVE MFB', code: 'E50' },
  { name: 'PODER FINANCE', code: 'F50' },
  { name: 'POINTONE MFB', code: 'E30' },
  { name: 'POLARIS BANK', code: '076' },
  { name: 'POLYBADAN MICROFINANCE BANK', code: '809' },
  { name: 'PREEMINENT MICROFINANCE BANK', code: 'D83' },
  { name: 'PREMIUMTRUST BANK', code: '105' },
  { name: 'PRESTIGE MICROFINANCE BANK', code: 'B43' },
  { name: 'PRISCO MICROFINANCE BANK', code: 'D56' },
  { name: 'PRISTINE DIVITIS MICROFINANCE BANK', code: '752' },
  { name: 'PROSPECTS MFB', code: 'F61' },
  { name: 'PROSPERITY MICROFINANCE BANK', code: 'F06' },
  { name: 'PROVIDUS BANK', code: '101' },
  { name: 'PRUDENT MICROFINANCE BANK', code: 'F64' },
  { name: 'PURPLEMONEY MFB', code: 'B44' },
  { name: 'PYRAMID MICROFINANCE BANK', code: 'F22' },
  { name: 'RAND MERCHANT BANK', code: '502' },
  { name: 'RAYYAN MICROFINANCE BANK', code: '956' },
  { name: 'READYCASH (PARKWAY)', code: 'C04' },
  { name: 'REFUGE MICROFINANCE BANK', code: 'B47' },
  { name: 'REHOBOTH MICROFINANCE BANK', code: '707' },
  { name: 'RELIANCE MICROFINANCE BANK', code: 'B49' },
  { name: 'RENMONEY MICROFINANCE BANK', code: 'B50' },
  { name: 'REPHIDIM MICROFINANCE BANK', code: 'B51' },
  { name: 'RETRUST MFB', code: 'E42' },
  { name: 'REVELATION MICROFINANCE BANK', code: 'F32' },
  { name: 'REX MICROFINANCE BANK', code: 'D71' },
  { name: 'RIC MFB', code: 'F92' },
  { name: 'RICHWAY MICROFINANCE BANK', code: 'B52' },
  { name: 'RIGO MICROFINANCE BANK', code: '720' },
  { name: 'RIMA MICROFINANCE BANK', code: 'D73' },
  { name: 'ROYAL BLUE MICROFINANCE BANK', code: 'F21' },
  { name: 'ROYAL EXCHANGE MICROFINANCE BANK', code: 'B53' },
  { name: 'RSU MICROFINANCE BANK', code: 'D23' },
  { name: 'RUBIES MFB', code: '587' },
  { name: 'RUN MFB', code: 'E49' },
  { name: 'SABI MFB', code: 'E11' },
  { name: 'SAFE HAVEN MICROFINANCE BANK', code: 'B54' },
  { name: 'SCIART FINANCE', code: 'E86' },
  { name: 'SHEPHERD TRUST MICROFINANCE BANK', code: 'C41' },
  { name: 'SIGNATURE BANK', code: '106' },
  { name: 'SIMPLE FINANCE LIMITED', code: '830' },
  { name: 'SIMPLIFY SYNERG', code: 'F78' },
  { name: 'SINCERE MICROFINANCE BANK', code: 'D88' },
  { name: 'SMARTCASH PAYMENT SERVICE BANK', code: 'C60' },
  { name: 'SOROMAN MICROFINANCE BANK', code: 'E51' },
  { name: 'SOURCE MICROFINANCE BANK', code: 'F04' },
  { name: 'SPARKLE', code: 'B59' },
  { name: 'SPECTRUM MICROFINANCE BANK', code: 'D76' },
  { name: 'SPRING SKY FINANCE', code: 'E80' },
  { name: 'STANBIC IBTC @EASE WALLET', code: 'C05' },
  { name: 'STANBIC IBTC BANK PLC', code: '039' },
  { name: 'STANDARD CHARTERED BANK NIGERIA LIMITED', code: '068' },
  { name: 'STANDARD MICROFINANCE BANK', code: '709' },
  { name: 'STB MORTGAGE BANK', code: 'C76' },
  { name: 'STERLING BANK PLC', code: '232' },
  { name: 'SUMMIT BANK', code: 'H06' },
  { name: 'SUNBEAM MICROFINANCE BANK', code: '700' },
  { name: 'SUNTOP MICROFINANCE BANK', code: 'F08' },
  { name: 'SUNTRUST BANK', code: '100' },
  { name: 'SURE ANCHOR MFB', code: 'D77' },
  { name: 'SWIFT TRUST MFB', code: 'E39' },
  { name: 'TAJ BANK', code: '302' },
  { name: 'TANGALE MICROFINANCE BANK', code: 'F03' },
  { name: 'TANGERINE MONEY', code: 'C82' },
  { name: 'TASUED MICROFINANCE BANK', code: '966' },
  { name: 'TATUM BANK', code: 'E96' },
  { name: 'TEASY MOBILE', code: 'C07' },
  { name: 'TEKLA FACTORING AND FINANCE LIMITED', code: '968' },
  { name: 'TELLERONE MFB', code: 'E91' },
  { name: 'TENN MFB', code: 'F91' },
  { name: 'THE BROOK FINANCE LIMITED', code: 'E29' },
  { name: 'THE MILLENNIUM MF', code: 'F85' },
  { name: 'THINK FINANCE MICROFINANCE BANK', code: '677' },
  { name: 'TITAN TRUST BANK', code: '102' },
  { name: 'TOFA MFB', code: 'F86' },
  { name: 'TOPRATE MICROFINANCE BANK', code: 'E83' },
  { name: 'TRANSPAY MFB', code: 'F82' },
  { name: 'TREASURES MICROFINANCE BANK', code: 'F35' },
  { name: 'TRINITY FINANCIAL', code: '957' },
  { name: 'TRIVES FINANCE COMPANY LTD', code: 'F48' },
  { name: 'TRUSTBANC J6 MICROFINANCE BANK LIMITED', code: '569' },
  { name: 'TRUSTBOND MORTGAGE(FIRST TRUST MORTGAGE)', code: '523' },
  { name: 'U AND C MICROFINANCE BANK', code: '789' },
  { name: 'UBA MONI', code: 'A99' },
  { name: 'UBJ MFB', code: 'E35' },
  { name: 'UCEE MFB', code: 'F80' },
  { name: 'UGA MICROFINANCE BANK', code: 'E78' },
  { name: 'UKPOR MFB', code: 'E95' },
  { name: 'ULTIMATE MICROFINANCEBANK', code: 'E77' },
  { name: 'UMMAH MICROFINANCE BANK', code: '961' },
  { name: 'UMUCHINEMERE PROCREDIT MICROFINANCE BANK', code: 'F29' },
  { name: 'UMUCHUKWU MICROFINANCE BANK', code: 'F15' },
  { name: 'UMUNRI MFB', code: 'E67' },
  { name: 'UMUOJI MFB', code: 'E88' },
  { name: 'UNAAB MICROFINANCE BANK', code: 'B66' },
  { name: 'UNIFUND MICROFINANCE BANK LIMITED', code: 'F01' },
  { name: 'UNILAG MICROFINANCE BANK', code: '728' },
  { name: 'UNILORIN MFB', code: 'F75' },
  { name: 'UNIMAID MICROFINANCE BANK', code: '705' },
  { name: 'UNION BANK OF NIGERIA PLC', code: '032' },
  { name: 'UNITED BANK FOR AFRICA PLC', code: '033' },
  { name: 'UNITY BANK PLC', code: '215' },
  { name: 'UNIUYO MICROFINANCE BANK', code: 'D95' },
  { name: 'UNLIMINT NIGERIA LIMITED', code: 'E46' },
  { name: 'URE MICROFINANCE BANK', code: 'F65' },
  { name: 'UVUOMA MFB', code: 'E37' },
  { name: 'UZONDU MICROFINANCE BANK', code: '892' },
  { name: 'VALE FINANCE LIMITED', code: 'F26' },
  { name: 'VFD MICROFINANCE BANK', code: 'B69' },
  { name: 'VICTORY MFB', code: 'H03' },
  { name: 'VISTA MICROFINANCE BANK', code: 'E82' },
  { name: 'VTNETWORK', code: 'C08' },
  { name: 'WALLET MFB', code: 'E66' },
  { name: 'WEMA BANK PLC', code: '035' },
  { name: 'WESLEY MFB', code: 'F70' },
  { name: 'WESTON-CHARIS MFB', code: 'E19' },
  { name: 'WHITECRUST FINANCE', code: 'E93' },
  { name: 'WRA MFB', code: 'F73' },
  { name: 'XPRESS WALLET', code: 'F09' },
  { name: 'YCT MICROFINANCE BANK', code: 'D63' },
  { name: 'YOBE MICROFINANCE BANK', code: 'F88' },
  { name: 'ZEDVANCE FINANCE LIMITED', code: 'F96' },
  { name: 'ZENITH BANK PLC', code: '057' },
  { name: 'ZENITH EAZY WALLET', code: 'F28' },
  { name: 'ZENITH MOBILE', code: 'C10' },
  { name: 'ZIKORA MICROFINANCE BANK', code: 'D42' },
  { name: 'ZITRA MFB', code: 'F98' },
];
